# Generated by Django 2.1.7 on 2019-02-13 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_auto_20190213_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
