# Generated by Django 2.1.7 on 2019-02-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0003_grocery_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='completed',
        ),
    ]
