# Generated by Django 2.1.7 on 2019-02-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0004_remove_grocery_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
